AZURE_LOCATION: 'westus2'
RESOURCE_NAME_PREFIX: 'sarapim1'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'sar-demo-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'none'
CICD_AGENT_TYPE: 'none'
CERT_TYPE: 'selfsigned'